### ISSUE TITLE
Add TSTL

### ISSUE THREAD

**Issue by agroce** [jmid/pbt-frameworks#5]
When you get a chance, would you add TSTL (https://github.com/agroce/tstl) ?  Python / integrated shrinking / no state machines

(No EDSL)

thanks!

**Comment by jmid** [comment]
Done! I've also added the *EDSL* and *coverage* columns discussed elsewhere.
I noticed that TSTL and Echidna's API (transition system) tests are (almost if not) the same as what people in the QuickCheck-family refer to as *'state-machine'*-tests - and have therefore marked them as such.

**Comment by agroce** [comment]
Thanks very much!

Ah, true, good point.  The "(guarded) API call sequences" thing at minimum makes it 1) easy to do state-machine based testing and 2) is what people want it for in the Quick-Check world, other than the fancy parallel stuff like Hypothesis has now.

Probably should in that case add the same state machine checkmark to DeepState, since the `OneOf` construct that takes a series of lambdas basically supports the same thing, via a slightly more flexible mechanism where the test harness can further structure the sequencing/machine into a series of bounded machines.

**Comment by jmid** [comment]
I agree that DeepState's `OneOf` makes it easier (and clearer) to express an arbitrary choice of "commands", as witnessed, e.g., by comparing https://github.com/agroce/rb_tree_demo/blob/master/easy_deepstate_fuzzer.cpp to
https://github.com/agroce/rb_tree_demo/blob/master/deepstate_harness.cpp
I furthermore agree it is an important generator "primitive". As such variations of `OneOf` exist in several PBT frameworks without a dedicated state-machine framework:
- `Gen.item` in Hedgehog for FSharp: https://hedgehogqa.github.io/fsharp-hedgehog/reference/hedgehog-gen.html#item
- `Gen.fromElements` in SwiftCheck https://github.com/typelift/SwiftCheck/blob/master/Sources/SwiftCheck/Gen.swift#L28
- `Gen.oneofl` in QCheck http://c-cube.github.io/qcheck/0.17/qcheck-core/QCheck/Gen/index.html#val-oneofl
- ...

With the right primitives one can indeed write tests of arbitrary 'API sequences' on a case-by-case basis:
- as you explain yourself https://blog.trailofbits.com/2019/01/22/fuzzing-an-api-with-deepstate-part-1/
- as also outlined in [the theft documentation](https://github.com/silentbicycle/theft/blob/master/doc/properties.md#testing-stateful-systems). 

I used (a variation of) `oneof` myself in [these lecture notes](https://janmidtgaard.dk/quickcheck/stmnote.pdf) - to pedagogically introduce students to state-machine frameworks: first I build a dedicated case-by-case generator to test hashtables (sec.2) and secondly I factor out the general and reusable pattern (sec.3 and onwards).

Overall however, I think it is a bit of a stretch to characterize `OneOf` as or equating it with a state-machine framework, e.g., compared to [RapidCheck's state machine framework for C++](https://github.com/emil-e/rapidcheck/blob/master/doc/state_ref.md). This phenomenon of factoring out generic and reusable parts is probably partly cultural, where functional programmers sometimes go to extremes. Finally, having a standard interface for state machine tests (and accompanying models of each software component) opens up for new opportunities, e.g, integration tests across components, as described in the seminal work on testing AUTOSAR software with QuickCheck https://vimeo.com/68331689  https://research.chalmers.se/en/publication/219899

**Comment by agroce** [comment]
I agree, actually!  I just was thinking if you were classifying TSTL and Echidna as having state machines, DeepState did.  I wouldn't have said they did, so thought you were using a very expansive notion of state machine checking.
